name: freelance_time_tracker
description: "A time management app aimed at freelancers that tracks working hours, project deadlines, and billing information. It generates invoices based on tracked hours and manages client communication in one place."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  pdf: ^3.11.1
  path_provider: ^2.1.4
  open_file: ^3.5.3
  table_calendar: ^3.1.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  timelines: ^0.1.0
  file_picker: ^8.1.2
  flutter_pdfview: ^1.3.2
  backdrop: ^0.9.1
  flutter_screenutil: ^5.9.3
  percent_indicator: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
